#!/bin/bash

# Load Xresources
xrdb -merge ~/.Xresources

# MacBook Air 'hot-key' bindings
xbindkeys

# disable screen 'blanking'
xset s off
xset -dpms
xset s noblank

# disable speaker 'beep'
xset -b

# enable transparency effects
xcompmgr &

# set wallpaper
feh --bg-scale $HOME/.wallpaper &

exec xmonad
