#!/bin/bash

set -e

# enable TV monitor
xrandr --output HDMI-1 --auto --above LVDS-1

# disable hardware 'beep' (not sure why I need to keep doing this)
xset b off

# refresh background image resolution
feh --bg-fill /home/awt/.wallpaper
