#!/bin/sh

#
# This script performs home-specific setup such as connecting to our wifi and
# mounting shared drives
#

sudo netctl stop-all
sudo netctl start home
sudo mount arch-home:/media /home/media
sudo systemctl restart mpd
