#!/bin/bash

journalPath="/home/awt/Dropbox/Notes/.journal/dailyJournal.txt"


function main() {
  insertDateHeader "$1"
  vim + $journalPath
}

function insertDateHeader() {
  location="$1"
  if [ -n "$location" ]; then
    headerString="`date` -- $location"
  else
    headerString="`date`"
  fi

  # formatting of here-file matters
  cat >> $journalPath << DONE

===============================================================================
$headerString
===============================================================================

DONE
}


main "$1"
