#!/bin/sh

# This benchmarking utility can be used to record the execution time of an
# arbitrary command. The output of the command is simply the execution time (in
# seconds), which makes it ideal for storing the output into a variable.

secondsSinceEpoch=`date +%s`
pid=`echo $$ | tr -d "\n"`

temporaryFileName="/tmp/$pid-$secondsSinceEpoch.runtime"
command="$*"

if (/usr/bin/time -f "%e" -o $temporaryFileName $command &> /dev/null); then
	cat $temporaryFileName | tr -d "\n"
else
	printf "INVALID_TIME_EXITED_WITH_NON-ZERO_STATUS"
fi

rm $temporaryFileName &> /dev/null
