#!/bin/bash

# Prints a shell prompt widget to stdout
#
# Widget displays:
#   Current Branch Name (if in a git repository)
#
# Widget is Color-Coded
#

cleanColor=$1
dirtyColor=$2
untrackedColor=$3
promptDefaultColor=$4

if [ -z "`git status 2>&1 | grep fatal`" ]; then
  gitBranch=`git branch | grep "\*" | tr -d '*' | sed 's/^\W//'`

  widgetColor=$promptDefaultColor
  if [ -n "`git status | grep "nothing to commit, working directory clean"`" ]; then
    widgetColor=$cleanColor
  elif [ -n "`git status | grep "Untracked files:"`" ]; then
    widgetColor=$untrackedColor
  elif [ -n "`git status | grep "Changes not staged for commit:"`" ]; then 
    widgetColor=$dirtyColor
  elif [ -n "`git status | grep "Changes to be committed:"`" ]; then
    widgetColor=$dirtyColor
  fi


  echo "$widgetColor[$gitBranch]$promptDefaultColor"
else
  echo ""
fi

