#!/bin/bash

# Prints a color-code to std-out based
# on the current battery percentage remaining.

high=$1
medium=$2
low=$3

powerPercentage=`powerPercentage`

if [ $powerPercentage -gt 50 ]; then
  echo $high
elif [ $powerPercentage -gt 15 ]; then
  echo $medium
else
  echo $low
fi
